### ISSUE TITLE
Positional sensing - How?

### ISSUE THREAD

**Issue by eriksonssilva** [josuelopezv/aDrums#4]
Hey @josuelopezv ! Thanks a lot for enriching the opensource world with such amazing project!
I'm wondering if you would be able telling us how to achieve positional sensing on a Snare pad?
Images/video would be awesome, but I know that you may not have them at hand, so a written description would help already.
Thanks a lot once again!

**Comment by josuelopezv** [comment]
Hi this protect is deprecated but i can guide you on how to get positional sending on the snare pad. Normally compatible e drum snares have a sensor in the center and 1 or more in the ring. Basically depending on the sensor reading frecuency you calculate the delay on the signal on each sensor and get the position the snare was hit. First a calibration reading is needed where the user hits the center of the drum so the system gets the baseline delay on the rim sensor and then hit the rim to get the baseline of the center sensor. Then just adjust depending on the reading delays

**Comment by eriksonssilva** [comment]
Hey Josue! Thanks a lot for your answer on this!
Ok, I get the overall picture.
Have you tried this with VST's such as Ez Drummer / Superior Drummer or any of those?
And last question: Would it be possible to use this with Uno/Mega with proper adjustments? I think yes, but I did not dive too deep.
Thanks!

**Comment by eriksonssilva** [comment]
Reading through the github page, I see you mention that the editor should be used for editing - and I assume it should also be used for "calibration", am I right?
However, I did not se any release for the apps. Should I build it myself? Sorry, C/C# are languages I'm not familiar!

**Comment by josuelopezv** [comment]
This can be achieved with arduino uno however stm32 or new arduino micro or leonardo compatible boards are faster (more cycles for reading from the ADC) for the same price as arduino uno. The VST that you choose doesn't affect, all of them use midi as the input so this is universal

**Comment by josuelopezv** [comment]
Yes the editor is to control the firmware for arduino device, what sensors are connected, what type of sensor and the parameters. This is saved on the eeprom of the arduino and the firmware converts the information received by the sensor to a midi note that any VST reads and play the corresponding sound

**Comment by eriksonssilva** [comment]
> This can be achieved with arduino uno however stm32 or new arduino micro or leonardo compatible boards are faster (more cycles for reading from the ADC) for the same price as arduino uno. The VST that you choose doesn't affect, all of them use midi as the input so this is universal

Ok, cool! I'll see if I can order a Leonardo then!

**Comment by eriksonssilva** [comment]
> Yes the editor is to control the firmware for arduino device, what sensors are connected, what type of sensor and the parameters. This is saved on the eeprom of the arduino and the firmware converts the information received by the sensor to a midi note that any VST reads and play the corresponding sound

Yeah, I think I understood this part! The only thing is tricky is that I don't see an exe or whatever so I can use on my computer.
So I'm assuming I have to build that or something like that?

**Comment by josuelopezv** [comment]
you can download the code and compile win.aDrumsManager it will generate the exe file that contains the manager that will install the firmware on your arduino and be able to configure it

**Comment by eriksonssilva** [comment]
Ok, I'll try to compile it here.
I've tried a bit but got several errors lol
I'll let you know if I need further assistance.
Thanks a lot, man! Have a good day!

**Comment by eriksonssilva** [comment]
Closing since nothing else needs to be done on @josuelopezv end.

**Comment by eriksonssilva** [comment]
Ok, I hate to be THAT guy. But I've downloaded Visual Studio and updated everything needed.
However, when compiling the file, this is all I see:
![image](https://github.com/josuelopezv/aDrums/assets/43449566/101cb3dc-e1ce-4aa4-9bcd-c014b8441542)

I know that my port is COM4, so I simply delete the COM1 and press "button2", but then I see this:

![image](https://github.com/josuelopezv/aDrums/assets/43449566/33b76660-b0d8-4b2a-b591-a508a3e815b7)

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Programmer Port not found
   at aDrumsLib.AvrUploader.Upload(String comPort, String UploaderExePath, String configFilePath, String HexFilePath) in C:\Users\Erikson\Desktop\aDrums-master\aDrumsLib\ArduinoUploader.cs:line 36
   at aDrumsLib.AvrUploader.Upload(String comPort) in C:\Users\Erikson\Desktop\aDrums-master\aDrumsLib\ArduinoUploader.cs:line 45
   at aDrumsLib.AvrUploader.Upload() in C:\Users\Erikson\Desktop\aDrums-master\aDrumsLib\ArduinoUploader.cs:line 54
   at aDrum.Form1.button2_Click(Object sender, EventArgs e) in C:\Users\Erikson\Desktop\aDrums-master\win.aDrumsManager\Form1.cs:line 43
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
aDrum
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Erikson/Desktop/aDrums-master/win.aDrumsManager/bin/Debug/aDrum.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
aDrumsLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Erikson/Desktop/aDrums-master/win.aDrumsManager/bin/Debug/aDrumsLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

Any ideas why this is happening? I've tried googling and chatgpt, but nothing seems to help.

Thanks and sorry once again!

**Comment by eriksonssilva** [comment]
Oh, and pressing button 1 immediately closes the program.

**Comment by snx778** [comment]
> this is all I see

@eriksonssilva, and i think that's all. I compiled the windows app and i saw the same (while the web app wasn't working at all), so i hope the author of the project will finish the work or at least explain us how to use the existing software to configure the module :)
